crate/pages/blog/readonly-crate-with-nginx-and-lua.html

added blogpost about how to make a read-only crate

---

crate/pages/docs/cloud/gce.html

https://github.com/crate/crate/issues/1577
Added reference to this information, and moved the content around to be easier to digest.

Add tabs to CGE page for Docker & CoreOS, reference CoreOS architectures

---

crate/pages/legal/notice.html
crate/pages/legal/notice.txt
crate/plugins/blog.py

and added support for automatic link creation for blog posts

updated NOTICE file

---

crate/pages/404.html
crate/pages/blog/how-is-crate-data-different-than-elasticsearch.html
crate/pages/search.html
crate/templates/google-search.html

also updated search and 404 pages to new layout

updated: how is crate different to elasticsearch

---

README.md

Apologies for the hot-fix style. As it was only to the read me, I left it that way. Not from now on…
Also, not entirely sure why there are other amendments here, I think I have some form of Markdown tidier running. Hasn't really made any difference but can redo if you want.

removed non-existant branch reference in documentation

---

crate/pages/events.html
crate/pages/events/artic15-2015.html
crate/pages/events/meetup-crate-persistence-with-docker.html
crate/pages/events/oscal-2015.html
crate/pages/index.html
crate/plugins/events.py
crate/templates/event-listing.html

show upcoming events ascending by date
show past events descending by date
show 3 most recent upcoming events on frontpage
improved some event pages

improved events listing

---

crate/pages/blog/using-sprint-data-crate-with-your-java-rest-application.html

added blog post about how to use spring data crate

---

crate/pages/events/docker-2nd-birthday.html

@ChrisChinchilla if you want to include a picture of the cake or the event you went to, that would be awesome

Adding docker birthday party event

---

crate/pages/events/arctic15-2015.html
crate/pages/events/iot-meetup-helsinki-2015.html
crate/pages/events/nosql-matters-dublin-2015.html
crate/pages/events/oscal-2015.html

My Name was showing up way too much on the events page so I did some editing. (Ignore the other two commits, they will return in another branch)

Chris remove

---

crate/pages/blog/docker-2nd-birthday.html

Beginnings and waiting on US team to finish.

docker 2nd party

---

crate/pages/docs.html

Spanky/release 0.47.8

---

crate/pages/blog/deploying-crate-with-docker-machine-swarm.html

I was following this tutorial and noticed a typo…

Fixed a typo

---

crate/pages/blog/451-research-impact-report.html

New blog post re: 451 Research's Impact Report

---

crate/pages/feed/index.xml

As per - https://trello.com/c/6zAeUyVo/1149-rss-feed-shows-old-tagline

Updated RSS title slogan

---

crate/pages/events/iot-world-sf.html

As you're offline for a bit, 'ack' this when you can @tbrandles

Added iot open source summit event

---

crate/pages/events/ln-enterprise-tech-may.html

And one more when you can @tbrandles

Added LETM event

---

crate/pages/events/docker-meetup-amsterdam-july-2015.html

And one more for you @spanktar

Added Amsterdam Docker meetup

---

crate/pages/events/idc-data-hub.html

Can you 'ack' and merge @spanktar ?

Added IDC Data Hub conf

---

crate/pages/events/integrate-scale-2015.html

One for you take a quick look and 'ack' at @spanktar

Added int and scale event

---

crate/pages/jobs.html
crate/pages/jobs/java-software-engineer.html

@chaudum can you give this tiny update a very quick 'ack'?

Fixed typos on job page

---

crate/pages/docs/install.html

Somehow I made the previous branch from something behind, and missed this file.

Missed a file for version bump

---

crate/pages/events/docker-meetup-london-july-2015.html

Can you take a look when you get a moment @spanktar ?

Added final details to Docker London meetup

---

crate/pages/events/enthusiasticon-2015.html

Hey @spanktar another 'ack' when you have time. I'm talking here, we might as well add it to site :)

added enthusiasticon

---

crate/pages/events/cloudopen.html

Solved my git troubles @spanktar so 'ack' and merge this when you can.

Added Cloud open event

---

crate/plugins/team.py

- Executives (and support)
- Core Devs (alpha order),
- Integrations (alpha order),
- Dev Relations (alpha order)

Reorder team:

---

crate/pages/events/containercon.html

Adding ContainerCon

---

crate/pages/events/voxxed-belgrade-2015.html

Added a new event @spanktar 'ack' and merge when you can :)

Added Voxxed days

---

crate/pages/try.html

(orhaned commit from ages ago, just ran across it)

Tweak wording of Try header

---

crate/pages/blog/pioneers-festival-final-8.html
crate/pages/events/collision-conf-2015.html
crate/pages/legal/notice.txt

Sorry to abuse this branch and re-open it again. I thought all was complete.

More 404s from prod (previus report was from staging)

---

crate/pages/install/index.html

added check java version check in bash script

removed java 7 version warning

---

crate/pages/blog/born-global-champion.html

Updated links and embedded tweet
Moving images and fixing links

Added Born global post

---

crate/pages/docs/faq.html
crate/pages/index.html
crate/static/css/crate.components.css
crate/templates/mailchimp-joins.html

Updated sign up to a mc subscribe box
mailchimp joins sign up component
Updated headline and button text for JOINs signup
Ready for ack @jodok

Added draft join signup pages

---

crate/pages/jobs.html
crate/pages/jobs/projektmanager.html
crate/static/css/crate.components.css
crate/templates/job.html

- Added header image for job spec
- Fixed "Apply" button
- Some spacing and font sizing

Header image for job specs

---

crate/pages/blog/avuxi-ranks-everywhere-on-earth-with-crate.html

Blog post update
case updates
Updated title based on feedback

Avuxi Case Study

---

.gitmodules
README.md
buildout-dev.cfg
buildout-production.cfg
buildout.cfg
versions.cfg

probably requires to clean jenkins workspace before running it

get rid of Cactus upstream and use egg instead

---

README.md
buildout.cfg
src/web/purge.py

Usage: `bin/py src/web/purge.py --api-key <KEY>`

added functionality to quickly purge fastly key

---

crate/pages/blog/analyzing-germanys-weather-with-crate.html

In case you want a quick look @mfelsche :)

Adding link to MW blog post

---

crate/pages/install/linux.html
crate/pages/install/overview.html

Regarding - https://trello.com/c/F8aBkOrl
How does this look to you @mfelsche ?

Adding new debian packages

---

pages/blog.html
pages/feed/index.xml
pages/index.html
pages/newsletter.html
pages/press.html
plugins/collections.py
templates/landing-lang.html

the `config.json` may look like:
```json
{
...
"collections": {
"blog": {
"title": "Blog",
"path": "blog/",
"template": "post.html",
"order": {
"key": "date",
"reverse": true
}
}
},
...
}
```
depends on: https://github.com/crate/crate-cactus/pull/18

make collections configurable via `config.json`

---

.gitignore
config.json

this file is ignored when building on Jenkins
it is however useful when developing locally

added default `config.json`

---

plugins/collection.py

- use relative path to table of content file in config.json
- ability to reverse the ordering

added relative path supp for toc file

---

pages/about/contact.html

remove irc channel and add gitter support

---

pages/index.html

* added new messaging
* added use cases
* removed old stuff

some changes for dockercon

---

pages/docs/index.html

what we got now:
* stable
* latest
* testing
i think that's good

fixed the links to versions.

---

pages/community/support.html

fix pricing links on support page

---

pages/blog/backing-up-and-restoring-crate.html

Hey @kovrus here's a draft of the blog post, I kept it pretty simple to lead people towards the docs, more of an announcement with a little detail.
We should probably wait until the feature makes stable branch?

Adding backup restore blog post

---

pages/community/support-enquiry.html

with support enquiries
~~DO NOT MERGE THIS BRANCH UNTIL THE REQUIRED FEATURES ARE RELEASED~~
`0.54` is already released as testing

added new page about how to provide system/cluster information

---

config.json
pages/a/improving-on-joins.html
pages/docs/getting-started/clients/java.html
pages/docs/getting-started/clients/php.html
pages/docs/getting-started/clients/python.html
pages/docs/getting-started/containers/docker.html
plugins/collection.py
templates/wf_head.html

@HymanKaplan I think you can handle an approval of this, it's pretty simple stuff, but just to do things right :)
Only this file you need to worry about - https://github.com/crate/crate-web/edit/cc/docker-revisit/pages/docs/getting-started/containers/docker.html?pr=/crate/crate-web/pull/292

Adding extra docker details

---

templates/wf_header.html

Forwarding docs links to getting started for now

---

pages/a/crate-with-docker-and-weave.html
pages/a/elasticsearch_in_crate_data.html
pages/community/support-enquiry.html
pages/docs/support/index.html

remove hipchat support channel and add slack community

---

pages/docs/getting-started/clients/index.html

@mfussenegger As you mentioned. In the long run I think I will create a 'tools' section for stuff like this, but this will do for now.

Update Vim text

---

pages/docs/getting-started/local/download-thanks.html

downloads Crate automatically and also referes to other platforms.

added `thanks for download` page

---

pages/docs/install/cloud/azure.html

Hey @mikethebeer Let me know if you think this works :)

Azure Docs Update

---

pages/a/sql-for-elasticsearch.html

For some context… This article was written some time ago and needed an update. The original was not written by me, so I've updated our feature list and re-written slightly, I'd appreciate opinions on if the content is still accurate and makes sense.
Bear in mind that this article is a search entry point to our website, so I've tried to make sure people can get an idea of who we are and what we do, when they likely have no idea.

Elastic Search SQL update

---

pages/a/funding-march-2016.html

fixed a link.

---

pages/docs/tools/index.html
pages/docs/tools/squirrel.html

improved tools overview page and re-added squirrel tutorial

---

pages/docs/clients/index.html
pages/docs/tools/index.html
templates/docs.html

@chaudum Made a few more changes than expected, but nice and tidy now… I think.

Consolidate and tidy tools page

---

pages/a/cratecube-intel-nuc-shoebox.html
pages/a/deploying-crate-with-docker-machine-swarm.html
pages/a/floss-weekly-interviews-crate-datas-jodok-batlogg.html
pages/a/snowsprint-2015.html

multiline html can cause rendering issues of markdown2 plugin
see https://github.com/trentm/python-markdown2/issues/188

put HTML code of video embed into single line

---

pages/docs/install/local/linux.html

update ubuntu install documentation

---

pages/a/azure-documentation.html
pages/a/beyond-whiteboards.html
pages/a/cratehack-day-1.html
pages/a/deploying-crate-with-docker-machine-swarm.html
pages/a/pioneers-festival-final-8.html
pages/a/using-crate-data-with-rails.html
pages/docs/install/containers/containership.html
pages/docs/scale/multi_zone_setup.html

@Nils-Magnus I have done some of these, so take a look and give me an 'ack' or not :)

Link fixes

---

_templates/docs.html
config.json
config/production.json
config/staging.json
pages/a/cr8-utility-scripts.html
pages/a/crate-flocker-weave-powerstrip-snowsprint.html
pages/a/managing-crate-with-mesos.html
pages/a/readonly-crate-with-nginx-and-lua.html
pages/a/using-crate-data-with-rails.html
pages/a/visualize-crate-data-with-metabase.html
pages/docs/clients/odbc.html
pages/docs/clients/php.html
pages/docs/install/cloud/index.html
pages/docs/install/local/index.html
pages/docs/install/local/linux.html
pages/docs/install/local/mac.html
pages/docs/install/local/tarball.html
pages/docs/install/local/windows.html

Slightly random one @celaus but as part of install tidy I wanted to get the words we use consistent.

Install consistency

---

static/js/benchmark.js

fixed invalid array definition in benchmark.js

---

pages/benchmark/index.html
static/js/benchmark.js

adopt frontend to use new column names

---

pages/benchmark/index.html
static/js/benchmark.js

depends on https://github.com/crate/crate-stresstest/pull/72
@m-kharbat please

changed grouping of benchmarks

---

static/js/benchmark.js

Enabled stdev error bars and disabled interactivity

---

pages/benchmark/index.html
static/css/crateio-rtd.css
static/js/benchmark.js

fix js error + set legend to bototm

---

pages/benchmark/index.html
static/js/benchmark.js

chart range

---

pages/benchmark/index.html
static/js/benchmark.js

add logscale

---

static/js/benchmark.js

change yaxis label to milliseconds

---

pages/docs/clients/jdbc.html

remove the jdbc driver class loading from
the landing page

update crate-jdbc landing page

---

config.json
config/production.json
config/staging.json

Updated testing to 0.57.2
